### PR TITLE
expand plugin patched to solve issue regarding unresolved placeholders.

### PR DESCRIPTION
**Pull request by peanutpi**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
I looks like a bunch of the unit tests are failing now. were you able to run the tests successfully locally?

**Comment by jonschlinkert** [comment]
@peanutpi ping

**Comment by peanutpi** [comment]
Sorry for the delay, but I'll create another pull request with all test passing successfully. So you can reject this pull request.

Sorry for the inconvenience.

**Comment by jonschlinkert** [comment]
no worries, thank you!

**Pull request closed without merging**
